In [2]:
import numpy as np

- __NumPy__ is a Python library.
- It is used for working with arrays.
- It is short for "Numerical Python".
- It is used for computation and processing of single and multi dimensional array of elements.
- Smaller memory consumption and better runtime behavior.

In [3]:
L = [1, 2, 3, 4, 5]
arr = np.array(L)
print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

In [5]:
type(L)

list

In [6]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [8]:
a = np.array([1, 2, 3, 4, 5], dtype=float)

In [9]:
a

array([1., 2., 3., 4., 5.])

In [10]:
a.ndim

1

In [11]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [12]:
c.ndim

2

In [13]:
a[2]

3.0

In [15]:
c[0][2]

3

NameError: name 'd' is not defined

In [17]:
d = np.array([[[[1, 2, 3], [4, 5, 6]]]])
print(d)
print(d.ndim)

[[[[1 2 3]
   [4 5 6]]]]
4


In [20]:
d[0][0][1][1]

5

In [21]:
a.shape

(5,)

In [22]:
c.shape

(2, 3)

In [23]:
d.shape

(1, 1, 2, 3)

In [24]:
arr.dtype

dtype('int32')

In [25]:
a.dtype

dtype('float64')

## Accessing/Changing specific elements, rows, columns, etc. in the NumPy array

In [26]:
a = np.array([[1, 2, 3, 4, 5], [8, 9, 10, 11, 12]])
print(a)

[[ 1  2  3  4  5]
 [ 8  9 10 11 12]]


In [27]:
a[0][1] = 200

In [28]:
a

array([[  1, 200,   3,   4,   5],
       [  8,   9,  10,  11,  12]])

## Zeros/Ones methods in NumPy

In [31]:
zero = np.zeros((3, 4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
zero.dtype

dtype('float64')

In [34]:
one = np.ones((3, 4), dtype=int)
one

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [35]:
np.full((3, 4), 60, dtype=int)

array([[60, 60, 60, 60],
       [60, 60, 60, 60],
       [60, 60, 60, 60]])

In [36]:
np.random.rand(3, 4)

array([[0.73662458, 0.79792688, 0.02043006, 0.7731532 ],
       [0.13990573, 0.01557554, 0.37056979, 0.94535989],
       [0.39112264, 0.71668026, 0.66886925, 0.15071443]])

In [39]:
np.random.randint(1, 100, (3, 4))

array([[87, 43, 15, 90],
       [38, 40, 36, 75],
       [86, 29, 37, 59]])

In [41]:
# Lists Vs Arrays
heights_list = [1.75, 1.80, 1.65, 1.90]
weights_list = [70, 80, 60, 90]

# This works with numoy
heights_array = np.array(heights_list)
weights_array = np.array(weights_list)

bmi_array = weights_array / (heights_array ** 2)
bmi_array

array([22.85714286, 24.69135802, 22.03856749, 24.93074792])